version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    environment:
      POSTGRES_DB: todo
      # You should definitely change the password in production
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
    ports:
      - "5454:5432"
###< doctrine/doctrine-bundle ###